#!/bin/sh
rm -rf build/lib
rm -rf /usr/lib/python2.7/site-packages/networking_ovn*
python setup.py install
rm -rf /var/log/neutron/server.log
systemctl restart neutron-server
vi /var/log/neutron/server.log
